version: '3'
services:
  xl-deploy:
    image: xebialabs/xl-deploy:8.6.1
    ports:
    - "4516:4516"
    environment:
    - ADMIN_PASSWORD=admin
    - ACCEPT_EULA=Y

  dockerproxy:
    image: tecnativa/docker-socket-proxy:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment: # warning this potentially opens up a security hole :)
      - AUTH=1
      - BUILD=1
      - COMMIT=1
      - CONTAINERS=1
      - EVENTS=1
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=1
      - PING=1
      - PLUGINS=1
      - POST=1
      - SECRETS=1
      - SERVICES=1
      - SWARM=1
      - SYSTEM=1
      - TASKS=1
      - VERSION=1
      - VOLUMES=1